version = 0.1
[default.deploy.parameters]
stack_name = "sns-cw-alert"
resolve_s3 = true
s3_prefix = "sns-cw-alert"
region = "us-east-1"
profile = "sandbox"
capabilities = "CAPABILITY_IAM"
image_repositories = []
